@startuml
'https://plantuml.com/use-case-diagram




User -> (trier les tâches)
User -> (Ajouter une tâche)
User -> (Supprimer une tâche)
User -> (Visualiser des tâches)

(trier les tâches)<|...(par nom de projet De A_Z)
(trier les tâches)<|...(par nom de projet De Z_A)
(trier les tâches)<|...(par date la plus ancienne)
(trier les tâches)<|...(par date la plus recente)



@enduml